### ISSUE TITLE
您好，我使用时运行不成功。。。

### ISSUE THREAD

**Issue by anyfar** [Kntt/vue-js-bridge#10]
先看配置
![image](https://user-images.githubusercontent.com/16009101/54269670-ba18d780-45b8-11e9-9de5-4599a48183c8.png)

引用
![image](https://user-images.githubusercontent.com/16009101/54269768-f0eeed80-45b8-11e9-96f7-184c2a2d70ad.png)

vue中mounted代码如下
![image](https://user-images.githubusercontent.com/16009101/54271124-df5b1500-45bb-11e9-83a7-1b36622c689b.png)
不管引用中delay设置多少，或者setTimeout设置多少，浏览器中总是最后显示[VueJsBridge] work in mock mode...
![image](https://user-images.githubusercontent.com/16009101/54271480-8dff5580-45bc-11e9-9936-065e9e7b7f22.png)

android代码顺序
使用andserver启动了一个内部服务器用来访问vue
andserver可以监听服务器已经开始启动，这时候loadUrl（vue页面）,并且不阻塞5秒后执行
![image](https://user-images.githubusercontent.com/16009101/54271870-580ea100-45bd-11e9-913f-80480ef82f36.png)

webViewRegister里执行例子中的代码
![image](https://user-images.githubusercontent.com/16009101/54266885-390b1180-45b3-11e9-8601-b136e13ef574.png)

最终代码Log信息如下
![image](https://user-images.githubusercontent.com/16009101/54272674-1c74d680-45bf-11e9-9651-4b72b4879b2e.png)

页面上按钮callNative代码
![image](https://user-images.githubusercontent.com/16009101/54272902-9311d400-45bf-11e9-8238-725002da3021.png)

执行后的Log信息
![image](https://user-images.githubusercontent.com/16009101/54272801-5940cd80-45bf-11e9-9e2e-6da9bbcfe039.png)

APP上code显示如下
![image](https://user-images.githubusercontent.com/16009101/54273039-ed129980-45bf-11e9-8d04-16400dd6d027.png)

哪里有错吗？为什么无效呢。。。新手捣鼓两天了。上面是下载的最新版重试的结果

**Comment by Kntt** [comment]
mock参数目前是true， 现在的配置是 mock是true 如果mockHandler存在就使用mock方式处理。
真机测试可以把mock参数修改为false。
建议通过环境变量判断， 避免生产环境忘记修改 @anyfar

**Comment by anyfar** [comment]
哦，小白一枚。设置mock后，还碰到个坑。。。
我添加了  webView.setWebViewClient(webViewClient);  发现也会导致失败，在shouldOverrideUrlLoading里 Log 显示 url:wvjbscheme://__BRIDGE_LOADED__。 即使后面return super.shouldOverrideUrlLoading(view, url);也不行。只好注释掉了setWebViewClient。
然后可以正常调用了，但发现有一处警告，WebViewJavascriptBridge WARNING: javascript handler threw."不清楚这个是什么意思
![image](https://user-images.githubusercontent.com/16009101/54290292-acc61200-45e5-11e9-82f9-e9d16169cea8.png)

**Comment by Kntt** [comment]
安卓方面的建议到https://github.com/lzyzsd/JsBridge这个repo去看看，安卓水平我不如你！ @anyfar
