### ISSUE TITLE
我还是不明白两边的注册顺序。。。

### ISSUE THREAD

**Issue by anyfar** [Kntt/vue-js-bridge#11]
我现在的流程是
创建并初始化WebView -> 
加载url -> 
200毫秒后，安卓端注册 webView.registerHandler("callNativeHandler", new BridgeHandler()...）->
Vue页面mounted()方法里this.$bridge.registerHandler('callJsHandler', (msg, callback)...) ->
1000毫秒后，Vue调用this.$bridge.callHandler(...)

控制台看到的结果是
安卓端注册
vue启动
js注册
然后就显示 java.io.FileNotFoundException: WebViewJavascriptBridge.js
chromium给出"Uncaught ReferenceError: WebViewJavascriptBridge is not defined"

这种情况是我注册的时机不对吗？

**Comment by Kntt** [comment]
我描述一下这个过程
1. android的webview加载url
2. 加载url过程中， js会在浏览器里面插入一个iframe加载和android端约定好的url（这里是异步）
3. android拦截到约定好的url， 初始化birdge
4. 前端通过初始化的birdge的regisiterHandler或者callHandler去和原生交互（这里容易出问题，就是前面异步加载导致的）

使用方式描述
1. 前端的registerHandler方法注册的方法 是给webview的callHandler使用的
2.相反。webview的registerHandler注册的方法是给前端callHandler使用的

所以使用时，无论android还是前端，都要在确保bridge已经初始化的前提下。
我最近在研究native端的实现，想要完善这个问题
