### ISSUE TITLE
jsbridge初始化方法处理有问题

### ISSUE THREAD

**Issue by Andy-Shangsa** [Kntt/vue-js-bridge#12]
VueJsBridgePlugin init：
![image](https://user-images.githubusercontent.com/24542738/59414727-a74eb280-8df4-11e9-9219-db7da6d54180.png)
WebViewJavascriptBridge适配IOS机型，JsBridge适配安卓机型，此处写法仅仅适配的是Ios手机
应该：
![image](https://user-images.githubusercontent.com/24542738/59415016-47a4d700-8df5-11e9-8e32-3ed19e0c1021.png)

![image](https://user-images.githubusercontent.com/24542738/59414992-3bb91500-8df5-11e9-916e-d59cfba3b61d.png)

**Comment by Andy-Shangsa** [comment]
WebViewJavascriptBridge的源码处理ios兼容性，此处需要判断ua，区分安卓机型

**Comment by Kntt** [comment]
感谢提醒， 稍后我会处理
