### ISSUE TITLE
【Hybird】数据交互问题

### ISSUE THREAD

**Issue by Jerrodly** [Kntt/vue-js-bridge#17]
@Kntt ，从文档上看，
1、只看到h5提供数据的两种方法给移动端，但是移动端不知道怎么接收，
2、如果移动端要传输数据给h5，h5怎么接收处理数据

**Comment by Kntt** [comment]
文档只描述了，这个插件的使用方法，app端发送消息可以看example里面的例子，ios和android是其他的两个仓库，建议去看看

**Comment by Jerrodly** [comment]
@Kntt  谢谢
