### ISSUE TITLE
[VueJsBridge] Start calling NativeHandler with payload: 之后没反应，在app的环境中！

### ISSUE THREAD

**Issue by Jiyr0119** [Kntt/vue-js-bridge#18]
async callNative() {
      try {
        await this.$bridge
          .callHandler({
            type: "Log",
            data: {
              name: "test js bridge"
            }
          })
          .then(res => {
            console.log("native-res", res);
            this.code = res;
          });
      } catch (error) {
        console.log("error", error);
      }
    }

Vue.use(VueJsBridge, {
  debug: true,
  nativeHandlerName: "SLJsBridge",
  mock: false,
  mockHandler(payload, next) {
    // mock by payload
    // call next(data) to mock data
    next(Object.assign({ form: "native" }, payload));
  }
});

然后原生同事那边约定好 这个名字  但是调用的时候就 打印start calling nativeHandler with payload 之后就没有反应了  但是直接 用 SLJsBridge.Log() 就可以调用成功。原生那边应该怎么写呢  还是现在写的这些有问题

**Comment by Kntt** [comment]
@Jiyr0119 你可以让原生的同事参考下  这个库对应的几个原生库，是否和他们使用的一致。
听你的描述，你们使用的bridge方案，可能是注入js的方式的

**Comment by Jiyr0119** [comment]
他们使用的是原生，说这个库对应的原生库在他们来说是第三方，他们原生开发规范里面不太愿意用第三方的库。因为是sdk之类的...

**Comment by Kntt** [comment]
@Jiyr0119 那估计是没办法使用了，实现方式不一样，没办法配合使用

**Comment by Jiyr0119** [comment]
原生那边改了，但是调用ios没问题   调用 安卓的时候会[VueJsBridge] Start calling NativeHandler with payload: 然后没反应 请问这是什么原因呀   ios 那边是没问题的
