### ISSUE TITLE
ios调用没问题，安卓卡在start calling 并没有走到成功。

### ISSUE THREAD

**Issue by Jiyr0119** [Kntt/vue-js-bridge#19]
callNative() {
      console.log("click");
      try {
        this.$bridge
          .callHandler({
            type: "Log",
            data: {
              name: "test js bridge"
            }
          })
          .then(res => {
            console.log("native-res", res);
            this.code = res;
          });
      } catch (error) {
        console.log("error", error);
      }
    }

------------------------
这段代码 ios 可以走到.then 但是 安卓走不进来

**Comment by Kntt** [comment]
@Jiyr0119 
需要ios和安卓统一下，不能各自做自己的

**Comment by Jiyr0119** [comment]
谢谢了  那个库的 aar 包有问题   复制他代码就没问题
