### ISSUE TITLE
您好,安卓调用H5提供的方法,调不通,请问您有尝试过吗?

### ISSUE THREAD

**Issue by youdianfan** [Kntt/vue-js-bridge#7]
您的东西,我研究了好几天了,跟IOS调试两个方法都没有问题,但是安卓端调取我的方法调不通

**Comment by youdianfan** [comment]
我具体在描述一下问题

**Comment by youdianfan** [comment]
第一:我是H5端用的是vue开发 用的这个vue-webview-js-bridge

**Comment by youdianfan** [comment]
一:我是H5端用的是vue开发 用的这个vue-webview-js-bridge
二:安卓端用的就是你的示例代码
三:我的注册方法是放在vue组件生命周期mounted中的
四:经过测试我们发现要在 H5页面手动点击再次注册一下registerHandler,安卓端才可以调用方法,或者写一个定时器延迟几秒注册registerHandler方法,安卓就可以调用我提供的方法了

请问您有出现这个问题吗?或者如何解决的?

**Comment by Kntt** [comment]
@youdianfan 我刚试了下确实有点问题， 已经找到原因了 稍晚点我会修复这个问题

**Comment by youdianfan** [comment]
感谢感谢,大概要多久呢.我们是小团队,技术能力有限,这个混合开发是刚刚做,技术也刚刚起步,在搜索文章方案中,看到了您写的代码.就拿来用了.
项目比较急,希望您抽空可以解决下,谢谢!真是感谢! @Kntt

**Comment by Kntt** [comment]
@youdianfan 导致这个问题的原因是bridge的初始化需要时间，这个也是一直困扰我的问题，在我写这个插件之前就遇到这个问题，写这个插件目的也是要解决这个问题，目前看来这个问题在regisiterHandler中没得到解决，目前我想到的解决方案就是在regisiterHandler里面做延时处理。今晚我会重新调整下这个方法

**Comment by youdianfan** [comment]
好的,理解了!那就不是安卓端导致的,感谢您的解答,已经反馈!谢谢! 记得发版的时候 npm更新一下包! 谢谢! 大佬@Kntt
