### ISSUE TITLE
您好,我这边经过测试还是不行.

### ISSUE THREAD

**Issue by youdianfan** [Kntt/vue-js-bridge#9]
![image](https://user-images.githubusercontent.com/27018910/54249781-76a07800-457c-11e9-903c-09e7e06cafbb.png)
delay: 10000,参数我加到10秒还是不行.
我这边加载的url 是线上url链接,不是本地的url文件

- 
![image](https://user-images.githubusercontent.com/27018910/54249845-a0f23580-457c-11e9-9c2f-beaf76b14acb.png)
我这边自己加个setTimeout,然后把delay改成0毫秒,运行起来是没有问题的

能说一下您的代码环境吗?
您在之前是怎么处理的 ?
还有就是有其他的解决方案吗?

**Comment by Kntt** [comment]
您看下你的版本更新没有呢？ 还有个问题是android调用方法的时机是什么时候？ @youdianfan

**Comment by youdianfan** [comment]
![image](https://user-images.githubusercontent.com/27018910/54250448-c97b2f00-457e-11e9-9ccb-4b4a5024db40.png)
版本已经更新
安卓端是按钮触发  点击按钮触发调用的我的方法
用的就是你的安卓demo示例 @Kntt

**Comment by Kntt** [comment]
目前我用demo测试是好用的， 我得排查下。现在的处理办法就是, 注册时候利用settimeout延迟处理，需要手动hack了，200ms左右 @youdianfan

**Comment by Kntt** [comment]
之前我的处理方式就是在 app的根组件里面 App.vue里面统一处理注册的方法，通过settimeout处理的

**Comment by youdianfan** [comment]
好的,好的,希望您能完善这个问题,我这边安卓要改用方案了.感谢您的解答,以及帮助!谢谢

**Comment by youdianfan** [comment]
我现在是用mixins混入全局的
![image](https://user-images.githubusercontent.com/27018910/54251242-971f0100-4581-11e9-93eb-ced39487978e.png)
看这样只能是settimeout做延迟处理了.真心想不到好的方案

**Comment by Kntt** [comment]
@youdianfan mixin没必要吧， 这个方法初始化时候注册一遍就好了， 用混入的方式，就是每个组件mounted的时候都要注册一遍，应该是没必要的

**Comment by youdianfan** [comment]
只执行一次,我试过了,实际也就是挂在了app.vue上

**Comment by Kntt** [comment]
后面如果有什么好的解决方案欢迎pr

**Comment by youdianfan** [comment]
好的好的!感谢您的解答

**Comment by beiguancyc** [comment]
我说下我的经历，所用代码都是demo中提供。
在ios端无任何问题。
android端测试的时候，和delay参数的值关系很大，比如改成0的话ios正常，android无反应。

**Comment by Andy-Shangsa** [comment]
VueJsBridgePlugin 在init的时候，借鉴了WebViewJavascriptBridge，其实仅仅适配了ios机型，安卓低版本会出错（测试时4.x版本几乎必现），实际上不需要delay，针对安卓机型加上以下代码即可
![image](https://user-images.githubusercontent.com/24542738/59415695-8f782e00-8df6-11e9-9e32-f0131dae5ab1.png)

**Comment by Kntt** [comment]
@Andy-Shangsa 
已经根据你的说法做了优化。详情https://github.com/Kntt/vue-js-bridge/issues/12#issue-455594321
